language: elixir
elixir:
  - 1.7
env:
  - MIX_ENV=test
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - cp apps/clean_code_katas/config/travis-ci.exs apps/clean_code_katas/config/test.exs
  - mix ecto.create
  - mix ecto.migrate
script:
  - mix test